config:
  credentials:
  - id: https://github.com/PalomoIFCA/private-sqaaastesting
    password_var: gAAAAABp1Lbrj7x1voeFTlENO76TdyaViY97aQ_KO9UsILXnQjGyqQFUXejjyuh9USigGVw11niDiTdobHXTzBF04s7qgJt0SNBt2XSeLXDtLaNOhgyvcewXWyIL4K0Ong9ONY6nbwvq
    username_var: gAAAAABp1LbrWblyZIY223V0hFlRwBqkklaO_J_BYhZ3bAGWOyruuT9lHMd3TiUlQtrA6HcYGyFe2UPCUUz5r47rTrss59Y8VA==
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/private-sqaaastesting:
      branch: main
      credential_tmp: true
      repo: https://github.com/PalomoIFCA/private-sqaaastesting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-amethyst-barb.sh
        container: qc.acc_fuzzy-tan-akbash
  QC.Doc:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-magnolia-magpie.sh
        container: qc.doc_thirsty-red-millipede
      github.com/PalomoIFCA/private-sqaaastesting git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-fuchsia-bullfrog.sh
        container: qc.doc_flabby-persimmon-ocelot
      github.com/PalomoIFCA/private-sqaaastesting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-thistle-horse.sh
        container: qc.doc_chewy-jade-capuchin
  QC.Lic:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-white-kudu.sh
        container: qc.lic_lanky-ochre-birman
  QC.Sec:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting bandit:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-white-paradise.sh
        container: qc.sec_queasy-emerald-collie
  QC.Sty:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-taupe-birman.sh
        container: qc.sty_wimpy-olivine-chamois
  QC.Uni:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting pytest:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-magnolia-armadillo.sh
        container: qc.uni_geeky-firebrick-capuchin
  QC.Ver:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-ultramarine-rat.sh
        container: qc.ver_muzzy-harlequin-tzu
timeout: 5400
