config:
  credentials:
  - id: https://github.com/PalomoIFCA/private-sqaaastesting
    password_var: gAAAAABp8zfdKOd8JA7DoWd6ysKI4QT2qOeH_Hh0zmwHAEt0AVBnaDiYsKHHqo9cPBLVCKgv_XkDPb4RWFf79T_0wuQ-P6JmGmCL0KUKO0KVFhOcja06saY3muu8cQoa9ekeJ92_tdFd
    username_var: gAAAAABp8zfdzbDhDmoXd46-1PKENkiDRVXNUVYcPLCXkVx3eNDiUHnc5Q0L7yO5g-pM6O4liwFa1otpSoJUzkM2Q2mLnoj5Rg==
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/private-sqaaastesting:
      branch: main
      credential_tmp: true
      repo: https://github.com/PalomoIFCA/private-sqaaastesting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-sangria-chinook.sh
        container: qc.acc_nerdy-harlequin-labradoodle
  QC.Doc:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-bistre-foxhound.sh
        container: qc.doc_silly-mauve-caracal
      github.com/PalomoIFCA/private-sqaaastesting git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-celadon-liger.sh
        container: qc.doc_sloppy-aquamarine-numbat
      github.com/PalomoIFCA/private-sqaaastesting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-rose-ragdoll.sh
        container: qc.doc_gummy-russet-quoll
  QC.Lic:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-cinnamon-deer.sh
        container: qc.lic_sickly-gamboge-rottweiler
  QC.Sec:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting bandit:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-lime-dormouse.sh
        container: qc.sec_squeaky-malachite-hippopotamus
  QC.Sty:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-blue-shark.sh
        container: qc.sty_tasty-lemon-lemur
  QC.Uni:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting pytest:
        commands:
        - /usr/bin/env sh .sqa/script.homely-olive-cheetah.sh
        container: qc.uni_sleepy-orchid-blue
  QC.Ver:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-brass-cichlid.sh
        container: qc.ver_slaphappy-beige-serval
timeout: 5400
